// Auto-generated by generate-manifest.js — do not edit by hand.
var IMAGES_DATA = {
  "overwolf": [
    {
      "id": "ov-01",
      "file": "assets/images/overwolf/1_1 Overwolf-1.png",
      "label": "1:1 Overwolf 1",
      "layouts": [
        "left",
        "right",
        "center"
      ]
    },
    {
      "id": "ov-02",
      "file": "assets/images/overwolf/1_1 Overwolf.png",
      "label": "1:1 Overwolf",
      "layouts": [
        "left",
        "right",
        "center"
      ]
    },
    {
      "id": "ov-03",
      "file": "assets/images/overwolf/9_16 Overwolf-1.png",
      "label": "9:16 Overwolf 1",
      "layouts": [
        "left",
        "right",
        "center"
      ]
    },
    {
      "id": "ov-04",
      "file": "assets/images/overwolf/9_16 Overwolf.png",
      "label": "9:16 Overwolf",
      "layouts": [
        "left",
        "right",
        "center"
      ]
    }
  ],
  "tebex": [],
  "outplayed": []
};
